### ISSUE TITLE
Decider Modals: Not showing "Waiting for..." Modal

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#190]
This appears right when the player decides to buy time or not, but does not appear with the other modals

**Comment by jpailthorpe** [comment]
though this seems strange, in the oduble down phase the decider doesn't see the waiting modal because there is potential for the decider to get cut off and not read the whole text before seeing the modal cover their screen. There are definitely better ways to do this (thats one me) , but it does match the current design. so moving to done for now.
