### ISSUE TITLE
List of changes: Update templates + partials to match updated mockups

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#204]
These have specific updates to copy, placement, and layout. It is mostly copy, but a big change is timer size/feel. Lets make sure these are 1:1! These are all accurate and updated in zepplin. 

I will make a new issue when the last half of the screen updates are in.

**Comment by mattwbenson** [comment]
[ ] Implement background graphic with @head 
[ ] All buttons have thinner shadow, but thicker same-color bottom border
[ ] Deck selection has different color schemes per deck
[ ] Decider dialogue text needs to be 16px instead of 17.5px
[ ] The box containing the countdown timers no longer has a bottom border shadow
[ ] The red countdown circle now has a bottom border shadow

**Comment by esalling23** [comment]
@jpailthorpe the speech bubble is an image, so if the border got darker can we get a new svg for that?

**Comment by jpailthorpe** [comment]
dialog box svg has been exported (just commenting for records).
