### ISSUE TITLE
DC: After DC/reconnect, menu appears, but buttons are non-responsive

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#254]
I had a three-person game where one of the devices temporarily disconnected while I was taking a screencap. After I re-opened the app (for iOS), the game behaved like the player had been reconnected on all other devices, but the menu modal was open on the device that had disconnected. A solid red bar was across the top of the modal, and none of the buttons were able to be pressed, preventing the user from actually pressing the "reconnect" button. The game then eventually treats that device as disconnecting again, and all players time out of the game.

**Comment by jpailthorpe** [comment]
saw this yesterday as well. Maybe has to do with the new error message in modal? @mattwbenson it would be helpful to try and recreate this with any console/layout information via dev tool screenshots if possible.

**Comment by jpailthorpe** [comment]
more info on this: 

nothing was wrong with the game. I opened the menu modal and tried clicking on one of the buttons before it fully animated in. nothing happened, and then all the of the buttons were non resposonsive. ON my other device, I opened the menu modal and waited until it was finished animating in. I then tried to press the back to game button and nothing happened. other buttons non responsive. last device opened menu modal and no buttons were responsive. 

not a touch target thing because I tried pressing everywhere, no dice. Also waited about 3-4 minutes and no response so there was no delay.

**Comment by jpailthorpe** [comment]
Note: clicking reconnect does nothing, and freezes all buttons in menu. other buttons work fine UNTIL you hit the reconnect button.

**Comment by jpailthorpe** [comment]
actually, when I open the menu one time and then hit back to game, the menu closes normally. After opening it a second time and trying to hit back to game, the menu does not close, and the buttons don't respond.

**Comment by jpailthorpe** [comment]
confirmed fix. Buttons are responsive on app (ios) and desktop.
