### ISSUE TITLE
Android phone kicked from game for screen-off, closes the session for all players

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#41]
The device that was kicked out was a Galaxy S6 running the game on Chrome. The browser was still the active app, but the screen powered off as a result of inactivity. This immediately disconnected the phone from the session, and ended the game for all other players. This is a UX problem at the very least, as it's frustrating for the player and unrealistic to expect users to monitor their devices constantly and keep them active.

**Comment by jpailthorpe** [comment]
This was probably due to the decider being the one whose device went to sleep. This is a core issue, but I am unsure how to solve it other than making sure player's screens don't fall asleep. 

The app "should" keep your screen awake, but when developing emerging citizens, we realized there are core device features that override us, such as low power mode on iphones. 

Overall, the game in essence is behaving the way the design has instructed it to. We will have to think a bit more about this decider dropping = game restarting thing.

**Comment by johnnycrich** [comment]
I am unable to get my Android to disconnect in this manner if I manually put it asleep, and it does not go sleep as intended once I touch the app screen.

**Comment by mattwbenson** [comment]
I've been trying to reproduce this, and at this point I think it was an issue with a VPN or some other security setting being enabled on my phone. Since changing those settings, I haven't been able to repeat this.

**Comment by jpailthorpe** [comment]
Magic fix 💯
